[workspace]
resolver = "2"
members = [
    "crates/rustypods",
    "crates/rustypodsd",
    "crates/rustypods-agent",
    "crates/rustypods-proto",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Nick"]

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "process", "io-util", "io-std", "sync", "time", "signal"] }
tokio-stream = { version = "0.1", features = ["net"] }
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
prost = "0.14"
tonic = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"
protoc-bin-vendored = "3"
tower = "0.5"
http = "1"
hyper-util = { version = "0.1", features = ["tokio"] }
libc = "0.2"
zbus = { version = "5", default-features = false, features = ["tokio"] }

rustypods-proto = { path = "crates/rustypods-proto" }
